name: 'Yocto Build'
description: 'a rule to build a yocto build in a container with all of the yocto dependancies'
inputs:
  yocto-target:  # id of input
    description: 'what build name to give to bitbake'
    required: true
    default: 'core-image-minimal'
  yocto-build-config: 
    description: 'what profile you want to load the configuration for'
    required: true
  yocto-build-script: 
    description: 'what script to run to set the environment'
    default: 'sources/poky/oe-init-build-env'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.yocto-target }} ${{ inputs.yocto-build-script }} ${{ inputs.yocto-build-config }}